WarriorMachinesLaravel:
  image: warriormachines/warriormachines-laravel:latest
  volumes:
   - ./laravel:/var/www/html

WarriorMachinesNginx:
  external_links:
   - mysql-database
  image: warriormachines/warriormachines-nginx:latest
  links:
   - WarriorMachinesPhpFpm
  ports:
   - "80"
  volumes_from:
   - WarriorMachinesLaravel

WarriorMachinesPhpBb:
  image: warriormachines/warriormachines-phpbb:latest
  volumes:
   - ./laravel/public/discuss:/var/www/html/public/discuss

WarriorMachinesPhpFpm:
  image: warriormachines/warriormachines-php-fpm:latest
  volumes_from:
   - WarriorMachinesLaravel
